// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaWebApp.Datos;

#nullable disable

namespace PruebaWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240701223329_datos")]
    partial class datos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PruebaWebApp.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Categoria normal",
                            Nombre = "Estandar"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Categoria premium",
                            Nombre = "Premium"
                        });
                });

            modelBuilder.Entity("PruebaWebApp.Models.Oficina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasFilter("[UsuarioId] IS NOT NULL");

                    b.ToTable("Oficinas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Calle 123",
                            Nombre = "Oficina 1",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Avenida 456",
                            Nombre = "Oficina 2"
                        });
                });

            modelBuilder.Entity("PruebaWebApp.Models.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proyectos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Descripción del Proyecto 1",
                            Nombre = "Proyecto 1"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Descripción del Proyecto 2",
                            Nombre = "Proyecto 2"
                        });
                });

            modelBuilder.Entity("PruebaWebApp.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Perez",
                            CategoriaId = 1,
                            Cedula = "12345678",
                            Nombre = "Juan"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Gomez",
                            CategoriaId = 2,
                            Cedula = "87654321",
                            Nombre = "Maria"
                        });
                });

            modelBuilder.Entity("PruebaWebApp.Models.UsuarioProyecto", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario", "IdProyecto");

                    b.HasIndex("IdProyecto");

                    b.ToTable("UsuarioProyectos");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            IdProyecto = 1
                        },
                        new
                        {
                            IdUsuario = 1,
                            IdProyecto = 2
                        },
                        new
                        {
                            IdUsuario = 2,
                            IdProyecto = 1
                        });
                });

            modelBuilder.Entity("PruebaWebApp.Models.Oficina", b =>
                {
                    b.HasOne("PruebaWebApp.Models.Usuario", "Usuario")
                        .WithOne("Oficina")
                        .HasForeignKey("PruebaWebApp.Models.Oficina", "UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PruebaWebApp.Models.Usuario", b =>
                {
                    b.HasOne("PruebaWebApp.Models.Categoria", "Categoria")
                        .WithMany("Usuarios")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("PruebaWebApp.Models.UsuarioProyecto", b =>
                {
                    b.HasOne("PruebaWebApp.Models.Proyecto", "Proyecto")
                        .WithMany("UsuarioProyectos")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PruebaWebApp.Models.Usuario", "Usuario")
                        .WithMany("UsuarioProyectos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PruebaWebApp.Models.Categoria", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("PruebaWebApp.Models.Proyecto", b =>
                {
                    b.Navigation("UsuarioProyectos");
                });

            modelBuilder.Entity("PruebaWebApp.Models.Usuario", b =>
                {
                    b.Navigation("Oficina");

                    b.Navigation("UsuarioProyectos");
                });
#pragma warning restore 612, 618
        }
    }
}
